// Generated by build_demo_font.py from cipher_demo.py. Do not hand-edit.
// Indexed by (keycode - KC_A), i.e. cipher_seq[0] is 'a'.
#pragma once

static const char *const cipher_seq[26] = {
    "kkk"  /* a */,
    "kkq"  /* b */,
    "kkx"  /* c */,
    "kkz"  /* d */,
    "kkj"  /* e */,
    "kkv"  /* f */,
    "kkw"  /* g */,
    "kqk"  /* h */,
    "kqq"  /* i */,
    "kqx"  /* j */,
    "kqz"  /* k */,
    "kqj"  /* l */,
    "kqv"  /* m */,
    "kqw"  /* n */,
    "kxk"  /* o */,
    "kxq"  /* p */,
    "kxx"  /* q */,
    "kxz"  /* r */,
    "kxj"  /* s */,
    "kxv"  /* t */,
    "kxw"  /* u */,
    "kzk"  /* v */,
    "kzq"  /* w */,
    "kzx"  /* x */,
    "kzz"  /* y */,
    "kzj"  /* z */
};
