// Cipher logic for the Souls Only demo, merged into the Keychron V1 Max keymap.
// See demo/BUILD.md. cipher_table.h is generated by tools/make_qmk_table.py.
//
// Behaviour in cipher mode (toggle: Right Ctrl):
//   * Any printable key (bare or shifted) emits its character's codes: a random
//     left code then a random right code (homophones). Uppercase = Shift+letter,
//     symbols = Shift+digit / punctuation keys.
//   * Space emits the space character's 4-char code.
//   * Enter emits a real newline plus KB_PAD_COUNT pad chars (stays 4-aligned).
//   * Backspace sends 4 backspaces; Left/Right arrow send 4 moves (edit/navigate
//     by whole logical characters).
//   * A re-entrancy guard means the keystrokes WE emit are not re-ciphered.
//   * Keys pressed with Ctrl/Alt/GUI pass through. Cipher off = normal keyboard.

#include QMK_KEYBOARD_H
#include "cipher_table.h"   // generated: kb_left, kb_right, kb_index, KB_PAD...

static bool cipher_on = false;
static bool kb_emitting = false;   // re-entrancy guard
static bool rng_seeded = false;

static void emit_char(int idx) {
    send_string(kb_left[idx][rand() % KB_HOMOPHONES]);
    send_string(kb_right[idx][rand() % KB_HOMOPHONES]);
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (kb_emitting) return true;   // let our own emitted keystrokes through

    if (keycode == KC_RCTL) {
        if (record->event.pressed) cipher_on = !cipher_on;
        return false;
    }
    if (!cipher_on || !record->event.pressed) return true;

    uint8_t mods = get_mods() | get_weak_mods();
    bool shifted = (mods & MOD_MASK_SHIFT) != 0;
    if (mods & ~MOD_MASK_SHIFT) return true;   // Ctrl/Alt/GUI shortcuts pass through

    bool edit = (keycode == KC_BSPC || keycode == KC_LEFT ||
                 keycode == KC_RIGHT || keycode == KC_ENT);
    int idx = -1;
    if (!edit) {
        idx = kb_index(keycode, shifted);
        if (idx < 0) return true;              // not a ciphered key -> normal
    }

    if (!rng_seeded) { srand(timer_read32()); rng_seeded = true; }

    kb_emitting = true;
    if (keycode == KC_BSPC) {
        // Navigation/edit: KEEP the user's mods so Shift+Backspace and (below)
        // Shift+Arrow behave normally. We do not emit characters here, so a held
        // Shift cannot corrupt anything.
        for (int i = 0; i < 4; i++) tap_code(KC_BSPC);
    } else if (keycode == KC_LEFT) {
        // Mods intact: bare Left moves one logical character (4 stream chars);
        // Shift+Left EXTENDS the selection by one logical character.
        for (int i = 0; i < 4; i++) tap_code(KC_LEFT);
    } else if (keycode == KC_RIGHT) {
        for (int i = 0; i < 4; i++) tap_code(KC_RGHT);
    } else if (keycode == KC_ENT) {
        // Emits characters (newline + pad): clear the held Shift so it cannot
        // corrupt them, then restore.
        uint8_t s = get_mods(), sw = get_weak_mods();
        clear_mods(); clear_weak_mods();
        send_string("\n");
        for (int i = 0; i < KB_PAD_COUNT; i++) send_string(KB_PAD);
        set_mods(s); set_weak_mods(sw);
    } else {
        // Emits the cipher codes: clear the held Shift (used to type a capital or
        // symbol) so it cannot corrupt the emitted ASCII codes, then restore.
        uint8_t s = get_mods(), sw = get_weak_mods();
        clear_mods(); clear_weak_mods();
        emit_char(idx);
        set_mods(s); set_weak_mods(sw);
    }
    kb_emitting = false;
    return false;              // we handled it; suppress the original key
}

#ifdef RGB_MATRIX_ENABLE
// While cipher mode is on, flood the whole board blue as a "Souls mode" tell.
// Returning false skips the keyboard's own indicator overlay so the blue is
// solid; when cipher is off we return true and normal RGB resumes.
bool rgb_matrix_indicators_user(void) {
    if (cipher_on) {
        rgb_matrix_set_color_all(0, 0, 255);   // R, G, B -> blue
        return false;
    }
    return true;
}
#endif
