// Cipher logic for the Monday demo, to be merged into the Keychron V1 Max
// keymap. This file is NOT a full keymap on its own. See demo/BUILD.md for the
// integration recipe.
//
// Behaviour:
//   * Right Ctrl toggles cipher mode on/off (no visual indicator in v1).
//   * In cipher mode, an unmodified lowercase letter key emits that letter's
//     3-character code (from cipher_table.h) instead of the letter. The demo
//     font ligates the code back into the readable letter.
//   * Any letter pressed with Ctrl/Alt/GUI/Shift passes through unchanged, so
//     shortcuts and capitals keep working.
//   * When cipher mode is off, the keyboard behaves completely normally.

#include QMK_KEYBOARD_H
#include "cipher_table.h"   // generated by demo/build_demo_font.py

static bool cipher_on = false;

// If the default Keychron keymap.c already defines process_record_user(),
// merge THIS body into it (keep its logic, add this at the top) rather than
// adding a second definition.
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    // Toggle key: Right Ctrl. Swallow both edges so it never acts as Ctrl.
    if (keycode == KC_RCTL) {
        if (record->event.pressed) {
            cipher_on = !cipher_on;
        }
        return false;
    }

    if (!cipher_on || !record->event.pressed) {
        return true;
    }

    // Only transform bare lowercase letters. Leave modified keys (shortcuts,
    // capitals) alone so the keyboard stays usable.
    if (keycode >= KC_A && keycode <= KC_Z) {
        uint8_t mods = get_mods() | get_weak_mods();
        if (mods == 0) {
            send_string(cipher_seq[keycode - KC_A]);
            return false;  // suppress the original letter
        }
    }

    return true;
}
