"""Build the standalone demo font and the matching QMK code table.

One command keeps the two halves of the demo in sync:
  * demo/SoulsDemo.ttf      the font (GSUB ligatures: 3-char code -> real letter)
  * demo/qmk/cipher_table.h the C table the QMK keymap emits (same codes)

Both are generated from demo/cipher_demo.py, so the keyboard and the font can
never drift apart. This does NOT import or modify src/cipher.py or
src/build_font.py, so it cannot collide with the in-flight PUA font work.

Run:
    python demo/build_demo_font.py
"""

from __future__ import annotations

import os

from fontTools.feaLib.builder import addOpenTypeFeatures
from fontTools.ttLib import TTFont

from cipher_demo import CODE_ALPHABET, demo_map

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BASE_FONT = os.path.join(ROOT, "base", "Jost-Regular.ttf")
OUT_FONT = os.path.join(HERE, "SoulsDemo.ttf")
OUT_FEA = os.path.join(HERE, "build", "demo.fea")
OUT_QMK = os.path.join(HERE, "qmk", "cipher_table.h")
OUT_JS = os.path.join(HERE, "cipher_table.js")

FONT_FAMILY = "Souls Demo"
FONT_PS_NAME = "SoulsDemo-Regular"


def generate_fea(font: TTFont) -> str:
    """liga feature: each 3-glyph ASCII code -> its real letter glyph."""
    base_cmap = font.getBestCmap()

    # Make sure the base font actually has a glyph for every code character and
    # every target letter before we reference them in FEA.
    for ch in set(CODE_ALPHABET):
        if base_cmap.get(ord(ch)) is None:
            raise RuntimeError(f"base font has no glyph for code char {ch!r}")

    lines = [
        "# Generated by build_demo_font.py from cipher_demo.py. Do not hand-edit.",
        "feature liga {",
    ]
    for letter, code in demo_map().items():
        letter_glyph = base_cmap.get(ord(letter))
        if letter_glyph is None:
            raise RuntimeError(f"base font has no glyph for letter {letter!r}")
        code_glyphs = " ".join(base_cmap[ord(ch)] for ch in code)
        lines.append(f"    sub {code_glyphs} by {letter_glyph};  # {code} -> {letter!r}")
    lines.append("} liga;")
    lines.append("")
    return "\n".join(lines)


def generate_qmk_header() -> str:
    """C header: the per-letter code strings QMK SEND_STRING will emit."""
    m = demo_map()
    rows = ",\n".join(f'    "{m[letter]}"  /* {letter} */' for letter in sorted(m))
    return (
        "// Generated by build_demo_font.py from cipher_demo.py. Do not hand-edit.\n"
        "// Indexed by (keycode - KC_A), i.e. cipher_seq[0] is 'a'.\n"
        "#pragma once\n\n"
        "static const char *const cipher_seq[26] = {\n"
        f"{rows}\n"
        "};\n"
    )


def generate_js() -> str:
    """JS map for the demo page's 'simulate keyboard' mode (same codes)."""
    m = demo_map()
    rows = ", ".join(f'{letter}: "{m[letter]}"' for letter in sorted(m))
    return (
        "// Generated by build_demo_font.py from cipher_demo.py. Do not hand-edit.\n"
        "// Mirrors the QMK table so 'simulate keyboard' matches the real keyboard.\n"
        f"const CIPHER_MAP = {{ {rows} }};\n"
    )


def set_font_names(font: TTFont) -> None:
    name = font["name"]
    name.setName(FONT_FAMILY, 1, 3, 1, 0x409)
    name.setName("Regular", 2, 3, 1, 0x409)
    name.setName(FONT_FAMILY, 4, 3, 1, 0x409)
    name.setName(FONT_PS_NAME, 6, 3, 1, 0x409)
    name.setName(FONT_FAMILY, 16, 3, 1, 0x409)


def build() -> None:
    font = TTFont(BASE_FONT)

    # Strip the base font's own layout so no stray ligatures/kerns interfere,
    # then add only our cipher feature. (Same approach as src/build_font.py.)
    for tag in ("GSUB", "GPOS"):
        if tag in font:
            del font[tag]

    fea = generate_fea(font)
    os.makedirs(os.path.dirname(OUT_FEA), exist_ok=True)
    with open(OUT_FEA, "w") as fh:
        fh.write(fea)
    addOpenTypeFeatures(font, OUT_FEA)
    set_font_names(font)
    font.save(OUT_FONT)

    os.makedirs(os.path.dirname(OUT_QMK), exist_ok=True)
    with open(OUT_QMK, "w") as fh:
        fh.write(generate_qmk_header())

    with open(OUT_JS, "w") as fh:
        fh.write(generate_js())

    print(f"wrote {OUT_FONT}")
    print(f"wrote {OUT_FEA}")
    print(f"wrote {OUT_QMK}")
    print(f"wrote {OUT_JS}")
    print(f"  {len(demo_map())} letters, {len(demo_map())} ligature rules")


if __name__ == "__main__":
    build()
