// Generated by build_demo_font.py from cipher_demo.py. Do not hand-edit.
// Mirrors the QMK table so 'simulate keyboard' matches the real keyboard.
const CIPHER_MAP = { a: "kkk", b: "kkq", c: "kkx", d: "kkz", e: "kkj", f: "kkv", g: "kkw", h: "kqk", i: "kqq", j: "kqx", k: "kqz", l: "kqj", m: "kqv", n: "kqw", o: "kxk", p: "kxq", q: "kxx", r: "kxz", s: "kxj", t: "kxv", u: "kxw", v: "kzk", w: "kzq", x: "kzx", y: "kzz", z: "kzj" };
