"""Generate demo/qmk/cipher_table.h from cipher/keyboard.py + cipher/qwerty.py.

One source of truth: the same code pools that drive the font's GSUB drive the
firmware. The header provides, indexed by character index into charset.CHARSET:
  * kb_left[idx][H] / kb_right[idx][H]  - the left/right code pools
  * kb_index(keycode, shifted)          - the char index a physical key types
  * KB_PAD / KB_PAD_COUNT               - the newline pad
The firmware emits a random left then a random right code per character.
"""

from __future__ import annotations

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from cipher import charset, keyboard as kb  # noqa: E402
from cipher import qwerty  # noqa: E402

OUT = os.path.join(ROOT, "demo", "qmk", "cipher_table.h")


def _pool_row(codes: list[str]) -> str:
    return "{ " + ", ".join(f'"{c}"' for c in codes) + " }"


def main() -> int:
    chars = charset.CHARSET  # index i == this char
    index_of = {ch: i for i, ch in enumerate(chars)}

    left_rows = []
    right_rows = []
    for ch in chars:
        letter = ch if ch != " " else "space"
        left_rows.append(f"    {_pool_row(kb.left_codes(ch))},  /* {letter} */")
        right_rows.append(f"    {_pool_row(kb.right_codes(ch))},  /* {letter} */")

    case_lines = []
    for keycode, (unshifted, shifted) in qwerty.LAYOUT.items():
        case_lines.append(
            f"        case {keycode}: return shifted ? {index_of[shifted]} "
            f": {index_of[unshifted]};"
        )
    case_lines.append(f"        case {qwerty.SPACE_KEYCODE}: return {index_of[' ']};")

    header = f"""// Generated by tools/make_qmk_table.py from cipher/keyboard.py + cipher/qwerty.py.
// Do not hand-edit. Indexed by character index into the cipher charset.
#pragma once

#include <stdint.h>
#include <stdbool.h>

#define KB_HOMOPHONES {kb.HOMOPHONES}
#define KB_NCHARS {len(chars)}
#define KB_PAD "{charset.PAD}{charset.PAD}"   // one backslash (C-escaped)
#define KB_PAD_COUNT 3

static const char *const kb_left[KB_NCHARS][KB_HOMOPHONES] = {{
{chr(10).join(left_rows)}
}};

static const char *const kb_right[KB_NCHARS][KB_HOMOPHONES] = {{
{chr(10).join(right_rows)}
}};

// Map a physical key + shift state to a character index, or -1 if not ciphered.
static int kb_index(uint16_t keycode, bool shifted) {{
    switch (keycode) {{
{chr(10).join(case_lines)}
    }}
    return -1;
}}
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(header)
    print(f"wrote {OUT} ({len(chars)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
