"""Generate the browser-demo assets for demo/index.html from cipher/keyboard.py.

Writes demo/cipher_table.js (the same left/right code pools the font and the QMK
firmware use) and copies the built variable font into demo/ so the demo folder
is self-contained.

    python -m fontbuild.build_keyboard   # build SoulsOnly.ttf + SoulsOnly-VF.ttf
    python tools/make_demo_assets.py
"""

from __future__ import annotations

import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from cipher import charset  # noqa: E402
from cipher import keyboard as kb  # noqa: E402

OUT_JS = os.path.join(ROOT, "demo", "cipher_table.js")
SRC_VF = os.path.join(ROOT, "dist", "SoulsOnly-VF.ttf")
DST_VF = os.path.join(ROOT, "demo", "SoulsOnly-VF.ttf")


def main() -> int:
    chars = charset.PRINTABLE  # space is not ciphered (stays a literal space)
    left = {ch: kb.left_codes(ch) for ch in chars}
    right = {ch: kb.right_codes(ch) for ch in chars}

    js = f"""// Generated by tools/make_demo_assets.py from cipher/keyboard.py. Do not hand-edit.
// The same code pools the Souls Only font and the QMK firmware use.
const KB_LEFT = {json.dumps(left)};
const KB_RIGHT = {json.dumps(right)};
const KB_PAD = {json.dumps(charset.PAD)};

// Encode one character the way the cipher keyboard does: a random left code
// then a random right code (homophones). Returns null for unsupported chars.
function cipherEncodeChar(ch) {{
  const l = KB_LEFT[ch], r = KB_RIGHT[ch];
  if (!l || !r) return null;
  return l[(Math.random() * l.length) | 0] + r[(Math.random() * r.length) | 0];
}}
"""
    with open(OUT_JS, "w") as fh:
        fh.write(js)
    print(f"wrote {OUT_JS}")

    if os.path.exists(SRC_VF):
        shutil.copyfile(SRC_VF, DST_VF)
        print(f"copied {DST_VF}")
    else:
        print(f"WARNING: {SRC_VF} missing; run 'python -m fontbuild.build_keyboard' first")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
