"""Generate demo/qmk/cipher_table.h from cipher/keyboard.py.

One source of truth: the same code pools that drive the font's GSUB ligatures
drive the keyboard firmware. Each letter gets a pool of left codes and a pool of
right codes; the firmware emits one random left then one random right, so the
typed bytes are different every time but always render to the right letter.
"""

from __future__ import annotations

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "demo", "qmk", "cipher_table.h")

import sys  # noqa: E402
sys.path.insert(0, ROOT)
from cipher import keyboard as kb  # noqa: E402


def _c_array(name: str, pools: list[list[str]]) -> str:
    rows = []
    for i, pool in enumerate(pools):
        letter = "abcdefghijklmnopqrstuvwxyz"[i]
        codes = ", ".join(f'"{c}"' for c in pool)
        rows.append(f"    {{ {codes} }},  /* {letter} */")
    body = "\n".join(rows)
    return (f"static const char *const {name}[26][KB_HOMOPHONES] = {{\n"
            f"{body}\n}};")


def main() -> int:
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    left = [kb.left_codes(ch) for ch in alphabet]
    right = [kb.right_codes(ch) for ch in alphabet]
    assert all(len(p) == kb.HOMOPHONES for p in left + right)

    header = f"""// Generated by tools/make_qmk_table.py from cipher/keyboard.py. Do not hand-edit.
// Indexed by (keycode - KC_A). Each letter owns a pool of left codes and a pool
// of right codes; the firmware emits one random left then one random right. The
// Souls Keys font ligates each 2-char code into a half-glyph; the two halves
// tile into the readable letter.
#pragma once

#define KB_HOMOPHONES {kb.HOMOPHONES}

{_c_array("kb_left", left)}

{_c_array("kb_right", right)}
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(header)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
