"""Build the cipher font from an OFL base font plus the cipher.py mapping.

What this produces (milestone 1):
  * A blank, zero-advance glyph for every PUA codepoint the cipher uses, mapped
    in `cmap`. So the RAW codepoint stream, if the font's ligatures are not
    applied, renders as nothing meaningful, and copy-paste yields PUA garbage.
  * A GSUB `liga` rule for each codepoint pair that collapses the two PUA input
    glyphs into the one real letter glyph borrowed from the base font. So a
    human reading rendered text sees the true letters.

Run:
    python src/build_font.py
Outputs:
    build/SoulsOnly.ttf   (the font)
    build/fea/cipher.fea  (the generated OpenType feature file, for inspection)
"""

from __future__ import annotations

import os

from fontTools.feaLib.builder import addOpenTypeFeatures
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._g_l_y_f import Glyph

from cipher import (
    all_pua_codepoints,
    letter_to_pairs,
    pua_glyph_name,
)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BASE_FONT = os.path.join(ROOT, "base", "Inter-Regular.ttf")
OUT_FONT = os.path.join(ROOT, "build", "SoulsOnly.ttf")
OUT_FEA = os.path.join(ROOT, "build", "fea", "cipher.fea")

FONT_FAMILY = "Souls Only"
FONT_PS_NAME = "SoulsOnly-Regular"


def add_blank_pua_glyphs(font: TTFont) -> None:
    """Add an empty, zero-advance glyph for every PUA codepoint, and map it."""
    glyf = font["glyf"]
    hmtx = font["hmtx"]

    for cp in all_pua_codepoints():
        name = pua_glyph_name(cp)
        if name in glyf:
            continue
        blank = Glyph()
        blank.numberOfContours = 0  # no outline -> renders nothing
        # Assigning to glyf[] already appends the name to the glyf table's own
        # glyph order; we sync the font-level order from it below.
        glyf[name] = blank
        hmtx[name] = (0, 0)  # zero advance width, zero left side bearing

    font.setGlyphOrder(list(glyf.glyphOrder))

    # Map each PUA codepoint to its blank glyph in every Unicode cmap subtable.
    cmap = font["cmap"]
    unicode_subtables = [t for t in cmap.tables if t.isUnicode()]
    if not unicode_subtables:
        raise RuntimeError("base font has no Unicode cmap subtable")
    for sub in unicode_subtables:
        for cp in all_pua_codepoints():
            sub.cmap[cp] = pua_glyph_name(cp)


def generate_fea(font: TTFont) -> str:
    """Build the FEA ligature feature: each PUA pair -> its real letter glyph."""
    base_cmap = font.getBestCmap()
    lines = [
        "# Generated by build_font.py from cipher.py. Do not edit by hand.",
        "# Each rule collapses a two-codepoint PUA pair into one real letter glyph.",
        "feature liga {",
    ]
    for letter, pairs in letter_to_pairs().items():
        letter_glyph = base_cmap.get(ord(letter))
        if letter_glyph is None:
            raise RuntimeError(f"base font has no glyph for {letter!r}")
        for first, second in pairs:
            g1 = pua_glyph_name(first)
            g2 = pua_glyph_name(second)
            lines.append(f"    sub {g1} {g2} by {letter_glyph};  # -> {letter!r}")
    lines.append("} liga;")
    lines.append("")
    return "\n".join(lines)


def set_font_names(font: TTFont) -> None:
    """Give the font a clean, recognisable name for @font-face."""
    name = font["name"]
    name.setName(FONT_FAMILY, 1, 3, 1, 0x409)   # Family
    name.setName("Regular", 2, 3, 1, 0x409)      # Subfamily
    name.setName(FONT_FAMILY, 4, 3, 1, 0x409)    # Full name
    name.setName(FONT_PS_NAME, 6, 3, 1, 0x409)   # PostScript name
    name.setName(FONT_FAMILY, 16, 3, 1, 0x409)   # Typographic family


def build() -> None:
    font = TTFont(BASE_FONT)

    add_blank_pua_glyphs(font)

    # Replace the base font's OpenType layout with only our cipher feature, so
    # there are no stray ligatures/kerns interfering with the proof. (A later
    # milestone can merge instead of replace.)
    for tag in ("GSUB", "GPOS"):
        if tag in font:
            del font[tag]

    fea = generate_fea(font)
    os.makedirs(os.path.dirname(OUT_FEA), exist_ok=True)
    with open(OUT_FEA, "w") as fh:
        fh.write(fea)

    addOpenTypeFeatures(font, OUT_FEA)
    set_font_names(font)

    os.makedirs(os.path.dirname(OUT_FONT), exist_ok=True)
    font.save(OUT_FONT)
    print(f"wrote {OUT_FONT}")
    print(f"wrote {OUT_FEA}")
    print(f"  {len(all_pua_codepoints())} PUA glyphs, "
          f"{sum(len(p) for p in letter_to_pairs().values())} ligature rules")


if __name__ == "__main__":
    build()
